<div class="container">
    <div class="row" style="margin-bottom:1em;">
        <div class="col-2"><img src="/img/startup.svg" height="90" align="centre" valign="middle"></div>
        <div class="col-10 align-center"><h1><?= $title;?></h1><h3><?= $sub; ?></h3></div>
    </div>
    <p class="lead">Before getting all carried away with the how, it's best to understand the basics of getting in to business. Firstly, you need to ask yourself why are you going in to business; what was the driving reasoning behind your decision? This is <a href="/startup/step/1">Step 1</a>.</p>
    <p class="lead">Have you checked to see how much competition you will be facing, or if there is even a market for your products and/or services? If there is a market, how big is it? And how much support will you get once you launch? Is there someone whom you can ask all these questions that you don't know the answers to <em>after</em> you've already invested your time, energy and effort (not to mention money)?</p>
    <p class="lead">Speaking of money, you should know that the minimum possible cost (in real cash) needed to start a company is around AU$750 at the time of writing (2018). And it isn't as simple as just filling in a form; starting a company is quite a complicated process. <a href="/startup/step/2">Step 2</a> in the journey is determining the best legal structure for your business, and then making that happen within the legal frameworks in Australia. Thankfully, it is the same no matter which State or Territory you choose to operate from.</p>
    <p class="lead">With legal structure comes the inevitable fees, and besides the registration fees of AU$488 payable to the <em>Australian Securities and Investment Commission</em> (ASIC), you are also going to need to pay for the professional services needed to legally and correctly draft your constition and first meeting of the Directors, among other mandatory filings. If you want to trade under a specific name, you will need to register that name too, and it attracts a filing fee of A$36/yr (or $84/3yr). Of course all these names must be unique, and acceptable!</p>
    <p class="lead">There are of course several online services that can guide you through the process of starting a company, but their objectives are often only to collect the minimum amount of data needed to legally begin the process of company formation; they have no interest in asking for what purpose, or whether or not the business is likely to succeed or fail.</p>
    <p class="lead">Our process will not only guide you through the process of starting a compnay, but also determine whether or not it is needed to open your businesses. We will also help you to determine if your potential business is what you thought it might be, and attempt to find examples of similar startups in local, national and international jurisdictions to use for comparison.</p>
    <p class="lead"><a href="/startup/step/3">Step 3</a> is to determine whether or not you are ready to face the competition, for it will be fierce, and the legal entities who challenge you exist only on paper, and have no emotions. To protect yourself, there are a number of digital readiness checks you need to complete in order to build a successful business.</p>
    <p class="lead">By comparing your business to other similar businesses, we will also attemt to provide you with some market insights in to competition and market statistics, both of which should be used as a guide for you to determine the liklihood of success in your chosen filed. Ideas are one thing, but business is another, so coaching and support should be one of the critical few in your list of 'things to secure before opening the doors'. This final stage is <a href="/startup/step/4">Step 4</a>.</p>
    <p class="lead">Venture Australia is committed to producing successful <em>businesses</em> with the ulitmate objective of creating employment opportunities for Australians and long term investment candidates for venture capital.</p>
    <h3>Your success, is our success.</h3>
</div>
